### ISSUE TITLE
Low performance & texture issues.

### ISSUE THREAD

**Issue by monarch322** [xoxor4d/gta4-rtx#1]
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/26b4ccb3-5f9e-4683-b703-3b669dfaf856" />

Disclaimer for this issue: during installation I was prompted with a download for DirectX June 2010 SDK but no instructions on where to install it so if any of the following issues are attributed to that, please follow up with instructions on where to install that SDK.

---
Specs:
AMD RYZEN 5 5600X
RTX 3080
32GB, 288 PIN, DDR4, 3600MHz
---

Extremely low frames (sub-20) even with the RTX menus showing at- or half VRAM usage.

Playermodel has no textures on clothing

Vehicle glass (including headlights, police light bars) is completely opaque, however allows light to shine through at night.

**Comment by monarch322** [comment]
> Please make sure that you have a bunch of usda files in rtx-remix/mods/gta4rtx/

Hi, thank you for the quick reply! 

I have 20 USDA files in that location. Is that the correct amount?

**Comment by TripleJ160** [comment]
> Hey from a quick glance it seems that either you or the installer failed to correctly install some of the files. Please make sure that you have a bunch of usda files in rtx-remix/mods/gta4rtx/
> 
> You can just re-extract the compatibility mod files manually and overwrite all when prompted.
> 
> As for the performance, lower your view distance and quality and don't be near much vegetation


I have the same issue. Windows are opaque. Recopied files over

<img width="3456" height="1172" alt="Image" src="https://github.com/user-attachments/assets/bf72c358-03a4-4d0b-a4ff-883967749288" />

**Comment by latent-variable** [comment]
I was able to fix the glass issue by reinstalling, but I selected to use full-screen instead of borderless window. For performance, I just toggled DLSS to Ultra Performance and added frame generation.

**Comment by xoxor4d** [comment]
If the glass is not translucent, that means that either something about the actual remix mod in `rtx-remix/mods` wasn't copied correctly or that your glass textures are in some way or form different. This difference results in a different texture hash and as such, remix is not modifying that material how its supposed to. 

- Do you guys have your texture quality in the in-game settings set to the highest? (Restart the game afterwards)
- Can you manually re-extract the `rtx-remix` folder and its files into your game folders?

**Comment by monarch322** [comment]
I believe the issue on my end with regard to the glass is from using the 'Project Glass' mod which enhances/fixes glass issues across the game.

Unrelated, I have two questions:
1. Do you have a Discord server for this mod?
2. How do I safely uninstall this mod from my game? It doesn't seem like my 3080 is able to run this mod at over 25-30 FPS so I am just going to uninstall.

**Comment by xoxor4d** [comment]
> I believe the issue on my end with regard to the glass is from using the 'Project Glass' mod which enhances/fixes glass issues across the game.

Yes. If something is modifying the original textures then the remix overrides will stop working.
As for your two questions, I've updated the readme on the main page which now includes a discord link and uninstall instructions

**Comment by TripleJ160** [comment]
> > I believe the issue on my end with regard to the glass is from using the 'Project Glass' mod which enhances/fixes glass issues across the game.
> 
> Yes. If something is modifying the original textures then the remix overrides will stop working. As for your two questions, I've updated the readme on the main page which now includes a discord link and uninstall instructions


I reinstalled the game and then installed the mod again. Windows are working fine now, so potentially older stuff can mess things up. This might be because I'm playing on ultrawide, but does the phone have anything to do with the RTX mod

<img width="2575" height="1439" alt="Image" src="https://github.com/user-attachments/assets/9f4a4cc3-13c2-446e-afa2-a3823846188c" />

**Comment by XxGoLdReIgNxX** [comment]
Okay so ive re installed the game and mod many multiple times. stared a new save. Still getting this issue. Fixed this issue once. But started again when trying to fix mem leak. Just curious what I could be doing wrong. Much love and appreciation in advance ✌️
